### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by Towux** [Tert0/fastapi-discord#154]
I dont understand how to work with "Depends"
Just help, how to get user info using access token?
Because "Example" code dont work, it writes "Unuuthenticated" error when i do isAuthenticated, get_user and get_guilds functions
maybe fastapi dont save my user in cache...

**Comment by Tert0** [comment]
The easiest way to test the example is with the intrgrated FastAPI docs at http://127.0.0.1:8000

1. Get the URL from the `/login` Endpoint
![image](https://github.com/user-attachments/assets/9c412726-66f7-4697-97ee-9b97687b9dca)
2. Use the URL from step one: Open it in a new Browser Tab and click on authorize
![image](https://github.com/user-attachments/assets/e5788361-be6a-49d7-95f9-ecb998c435cb)
3. You should get redirected to your callback url and see your tokens like this:
![image](https://github.com/user-attachments/assets/1ee289d4-64ff-49e2-bb0a-31da6a5b9248)
4. Use the "Authorize" Button of the FastAPI Docs and input your access_token
![image](https://github.com/user-attachments/assets/9fd7e692-056a-4059-8cc9-ab17f3bf993b)
![image](https://github.com/user-attachments/assets/6215c647-7d10-415c-9bd7-4e80d4117aae)
5. The `/authenticated` Endpoint should return true
![image](https://github.com/user-attachments/assets/6e15b96a-5ffc-416b-aeae-05fb5211de76)
6. You can now use the other endpoints
![image](https://github.com/user-attachments/assets/490ebe72-c611-4b9b-af1f-3c89807148b3)

If you develop a application for this you have to handle this in code.
You should provide the user with a Button opening the Discord URL.
When the callback is called you should save the tokens on the client and provide them on every request in the Authorization header.
