### ISSUE TITLE
Released version dependencies out of date

### ISSUE THREAD

**Issue by brodokk** [Tert0/fastapi-discord#183]
Hello,

I am trying to use your project but I am using poetry and I encounter the following problem:

```
Because no versions of fastapi-discord match >0.2.6.1,<0.3.0.0
 and fastapi-discord (0.2.6.1) depends on fastapi (0.112.0), fastapi-discord (>=0.2.6.1,<0.3.0.0) requires fastapi (0.112.0).
And because fastapi[standard] (0.115.5) depends on fastapi (0.115.5)
 and no versions of fastapi match >0.115.5,<0.116.0, fastapi-discord (>=0.2.6.1,<0.3.0.0) is incompatible with fastapi[standard] (>=0.115.5,<0.116.0).
So, because resonite-communities depends on both fastapi[standard] (^0.115.5) and fastapi-discord (^0.2.6.1), version solving failed.
```

To summary this, the release version 0.2.6.1 have out of date dependencies while it's not the case on the master branch ( https://github.com/Tert0/fastapi-discord/blob/master/requirements.txt )

It would be possible to publish a new release to fix this problem?

I suppose it would not be a bad idea to issue a new release each time the file requirements.txt is touched.

This would be an issue for any package manager who is trying to resolve dependencies issues.

For now I am using the master branch directly in my pyproject.toml file.

**Comment by Tert0** [comment]
I created an new release on PyPI: https://github.com/Tert0/fastapi-discord/releases/tag/v0.2.7

Currently I don't have much time to maintain this project and unfortunately I don't have a good solution to completely automate the release process. I would be happy to accept a PR.

**Comment by brodokk** [comment]
Thks!

This is understandable, sadly I think to automate the process this would require some work on someone with access to the PyPi account to configure. Or maybe no, I do not know.
