### ISSUE TITLE
How to use state parameter for callback

### ISSUE THREAD

**Issue by rudSarkar** [Tert0/fastapi-discord#6]
Hi,

As per the example from this module, I saw people use `state` parameter.

```python
@app.get("/callback")
async def callback(code: str):
    token, refresh_token = await discord.get_access_token(code)
    return {
        "access_token": token,
        "refresh_token": refresh_token
    }
```

Could you please elaborate? It will be helpful.

Thanks,
@rudSarkar

**Comment by Tert0** [comment]
I implmented a Feature to generate a OAuth2 Link with a State Parameter in #7.
To implement this in a FastAPI Project you probably need a Session System to save State Token(https://discord.com/developers/docs/topics/oauth2#state-and-security) but I'm not sure how implement this correctly.

**Comment by rudSarkar** [comment]
I am closing this Issue as you implemented the state param.
