### ISSUE TITLE
fastapi-discord not working with package uvicorn

### ISSUE THREAD

**Issue by LPSebi** [Tert0/fastapi-discord#64]
When I try to use uvicorn.run... I get `RuntimeError: no running event loop` 
but when I use uvicorn in the cli I don't get any errors.
Would it be possible to support the uvicorn package

**Comment by Tert0** [comment]
Should be fix in Version `v0.2.4`.
https://github.com/Tert0/fastapi-discord/releases/tag/v0.2.4
